#!/bin/bash

sudo su
apt-get upgrade -y
apt-get install awscli python-dev libxml2-dev libxslt1-dev libssl-dev build-essential virtualenv -qy
git clone https://github.com/gjehanin/ec2instances.info
cd ec2instances.info/
virtualenv env
source env/bin/activate
pip install -r requirements.txt
fab build
fab serve
